---
# tasks file for ansible-client-server-tests
- name: Install httpd
  ansible.builtin.package:
    name: httpd
    state: present

- name: Enable httpd service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: Put index.html
  ansible.builtin.copy:
    content: 'Hello from ansible'
    dest: /var/www/html/index.html
