---
lint: |
  set -e
  yamllint .
  ansible-lint -f full
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: server01
    docker_networks:
      - name: clientservertest
        ipam_config:
          - subnet: '172.40.0.0/16'
    networks:
      - name: clientservertest
        ipv4_address: '172.40.10.1'
    pre_build_image: false
    registry:
      url: registry.access.redhat.com
    image: ubi8/ubi-init
    privileged: true
    command: "/usr/sbin/init"
    groups:
      - servers
  - name: server02
    docker_networks:
      - name: clientservertest
        ipam_config:
          - subnet: '172.40.0.0/16'
    networks:
      - name: clientservertest
        ipv4_address: '172.40.10.2'
    pre_build_image: false
    registry:
      url: registry.access.redhat.com
    image: ubi8/ubi-init
    privileged: true
    command: "/usr/sbin/init"
    groups:
      - servers
  - name: client01
    networks:
      - name: clientservertest
        ipv4_address: '172.40.11.1'
    pre_build_image: false
    registry:
      url: registry.access.redhat.com
    image: ubi8/ubi-init
    privileged: true
    command: "/usr/sbin/init"
    groups:
      - client
provisioner:
  name: ansible
  inventory:
    host_vars:
      server01:
        ip: '172.40.10.1'
      server02:
        ip: '172.40.10.2'
      client01:
        ip: '172.40.11.1'
verifier:
  name: ansible
